import { Metadata } from 'next';
import { getAllReports } from '@/lib/reports';
import { ReportsArchiveClient } from '@/components/ReportsArchiveClient';

export const metadata: Metadata = {
  title: 'Daily Intelligence Archive',
  description:
    'Autonomous daily intelligence digests generated by the DevAtlas pipeline, recording ecosystem shifts, AI releases, and verified job trends.',
  openGraph: {
    title: 'Daily Intelligence Archive | DevAtlas',
    description:
      'Autonomous daily intelligence digests generated by the DevAtlas pipeline.',
    url: '/reports',
  },
  alternates: {
    canonical: '/reports',
  },
};

export default async function ReportsIndexPage() {
  const reports = await getAllReports();

  return (
    <div className="w-full px-4 md:px-8 xl:px-12 py-6 sm:py-10 space-y-8">
      {/* Section Header */}
      <div className="border-b border-double-rule-bottom pb-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <span className="stamp-badge mb-3 inline-flex">
              <span className="h-1.5 w-1.5 rounded-full bg-accent" />
              &sect; E. THE DETERMINISTIC ARCHIVE
            </span>
            <h1 className="font-serif text-3xl sm:text-5xl font-black text-foreground tracking-tight">
              DAILY INTELLIGENCE<br />
              <span className="font-editorial italic text-dateline">Archive &amp; Dispatches</span>
            </h1>
            <p className="mt-3 font-editorial text-sm sm:text-base text-muted max-w-xl leading-relaxed">
              Autonomous daily developer intelligence digests synthesized from verified feeds and committed directly to the repository via GitHub Actions.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <span className="border border-border px-4 py-2 font-mono text-[10px] font-bold tracking-[0.15em] uppercase text-foreground bg-card">
              {reports.length} Reports Published
            </span>
          </div>
        </div>
      </div>

      {/* Report Listings with Live Edge Sync */}
      <ReportsArchiveClient initialReports={reports} />
    </div>
  );
}
