export interface FallbackItem {
  _id: string;
  type: 'AI_TOOL' | 'JOB' | 'REPOSITORY' | 'NEWS' | 'SECURITY';
  title: string;
  description: string;
  summary: string;
  canonicalUrl: string;
  category: string;
  tags: string[];
  score: {
    total: number;
    freshness: number;
    popularity: number;
    developerValue: number;
    technologyImpact: number;
    reasons: string[];
  };
  job?: {
    company: string;
    location: string;
    remote: boolean;
    workMode: 'REMOTE' | 'HYBRID' | 'ON_SITE';
    region: 'INDIA' | 'GLOBAL_REMOTE' | 'NORTH_AMERICA' | 'EUROPE';
    experienceLevel: 'ENTRY' | 'MID' | 'SENIOR' | 'STAFF_PRINCIPAL';
    sourcePlatform: 'LinkedIn' | 'Company Careers' | 'Greenhouse' | 'Lever';
    employmentType: string;
    salary: string;
    skills: string[];
  };
  repository?: {
    ownerRepo: string;
    stars: number;
    forks: number;
    language: string;
    starsGrowth24h?: number;
  };
  tool?: {
    pricingModel: 'FREE' | 'FREEMIUM' | 'PAID' | 'OPEN_SOURCE';
    isOpenSource: boolean;
    hasApi: boolean;
  };
  publishedAt: string;
  status: string;
}

export const FALLBACK_ITEMS: FallbackItem[] = [
  // ==========================================
  // INDIA TECH HUBS & STARTUPS (BENGALURU, HYDERABAD, PUNE, GURUGRAM)
  // ==========================================
  {
    _id: 'job-in-001',
    type: 'JOB',
    title: 'Senior Backend Engineer - High Throughput Payments',
    description: 'Scale core payment transaction ledger handling peak volumes of 100,000+ financial TPS with strict ACID guarantees and sub-20ms p99 latency.',
    summary: 'Core engineering role designing mission-critical distributed payment systems with extreme reliability.',
    canonicalUrl: 'https://careers.cred.club/jobs/senior-backend-payments',
    category: 'Fintech & Payments',
    tags: ['golang', 'kafka', 'postgresql', 'distributed-systems', 'redis', 'india'],
    score: {
      total: 98,
      freshness: 99,
      popularity: 98,
      developerValue: 99,
      technologyImpact: 97,
      reasons: ['Elite fintech engineering culture', 'High volume low-latency architecture', 'Competitive compensation'],
    },
    job: {
      company: 'CRED',
      location: 'Bengaluru, India',
      remote: false,
      workMode: 'ON_SITE',
      region: 'INDIA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'LinkedIn',
      employmentType: 'Full-Time',
      salary: '₹40,00,000 - ₹60,00,000 / 40-60 LPA + ESOPs',
      skills: ['Go', 'Kafka', 'PostgreSQL', 'Redis', 'Distributed Systems'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-002',
    type: 'JOB',
    title: 'Staff Platform Infrastructure Engineer',
    description: 'Design multi-region cloud platform infrastructure on AWS and Kubernetes for payment gateway APIs serving 8M+ businesses across India and SEA.',
    summary: 'Architect resilient multi-tenant Kubernetes platform and service mesh for India largest fintech gateway.',
    canonicalUrl: 'https://razorpay.com/jobs/staff-platform-engineer',
    category: 'Cloud Infrastructure',
    tags: ['kubernetes', 'aws', 'golang', 'terraform', 'istio', 'india'],
    score: {
      total: 97,
      freshness: 97,
      popularity: 96,
      developerValue: 98,
      technologyImpact: 97,
      reasons: ['Tier-1 scale engineering', 'Modern cloud native stack', 'Leadership opportunity'],
    },
    job: {
      company: 'Razorpay',
      location: 'Bengaluru, India',
      remote: true,
      workMode: 'HYBRID',
      region: 'INDIA',
      experienceLevel: 'STAFF_PRINCIPAL',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '₹55,00,000 - ₹80,00,000 / 55-80 LPA + Stocks',
      skills: ['Kubernetes', 'Go', 'AWS', 'Terraform', 'Service Mesh'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-003',
    type: 'JOB',
    title: 'SDE-3 / Lead Backend Engineer - Delivery Routing Algorithms',
    description: 'Build real-time spatial dispatch algorithms and order batching engines optimizing delivery driver routing across 500+ Indian cities in real-time.',
    summary: 'Solve massive combinatorial optimization problems at lightning speed for instant hyper-local logistics.',
    canonicalUrl: 'https://careers.swiggy.com/jobs/sde-3-logistics',
    category: 'Logistics & Systems',
    tags: ['java', 'spring-boot', 'geospatial', 'redis', 'algorithms', 'india'],
    score: {
      total: 96,
      freshness: 96,
      popularity: 95,
      developerValue: 97,
      technologyImpact: 96,
      reasons: ['Massive consumer scale', 'High algorithmic complexity', 'Top tech compensation'],
    },
    job: {
      company: 'Swiggy',
      location: 'Bengaluru, India',
      remote: false,
      workMode: 'HYBRID',
      region: 'INDIA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'LinkedIn',
      employmentType: 'Full-Time',
      salary: '₹42,00,000 - ₹62,00,000 / 42-62 LPA + RSUs',
      skills: ['Java', 'Spring Boot', 'Kafka', 'Redis', 'Algorithms'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 7).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-004',
    type: 'JOB',
    title: 'Systems & Low-Latency Trading Platform Engineer',
    description: 'Engineer high-throughput market data websocket gateways, real-time OMS engines, and ultra-reliable trading APIs serving millions of concurrent retail investors.',
    summary: 'Zero-bloat engineering building lean, ultra-fast financial trading systems in Go and Python.',
    canonicalUrl: 'https://zerodha.com/careers/systems-engineer',
    category: 'Trading Infrastructure',
    tags: ['golang', 'python', 'postgresql', 'networking', 'websockets', 'india'],
    score: {
      total: 98,
      freshness: 98,
      popularity: 99,
      developerValue: 99,
      technologyImpact: 98,
      reasons: ['Elite developer freedom and culture', 'FOSS first philosophy', 'Exceptional work-life harmony'],
    },
    job: {
      company: 'Zerodha',
      location: 'Bengaluru, India / Remote',
      remote: true,
      workMode: 'REMOTE',
      region: 'INDIA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '₹35,00,000 - ₹55,00,000 / 35-55 LPA + Bonus',
      skills: ['Go', 'PostgreSQL', 'Python', 'WebSockets', 'Linux Networking'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 9).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-005',
    type: 'JOB',
    title: 'Senior Full Stack Engineer - 10-Min Delivery Engine',
    description: 'Architect customer-facing micro-frontends, dynamic inventory caching, and real-time order tracking pipelines handling 1M+ daily orders.',
    summary: 'High-velocity product engineering driving India fastest growing quick-commerce platform.',
    canonicalUrl: 'https://zeptonow.com/careers/senior-fullstack',
    category: 'Product Engineering',
    tags: ['react', 'nextjs', 'nodejs', 'typescript', 'redis', 'india'],
    score: {
      total: 95,
      freshness: 95,
      popularity: 94,
      developerValue: 96,
      technologyImpact: 95,
      reasons: ['Extreme business growth', 'Modern frontend & backend stack', 'Rapid ownership'],
    },
    job: {
      company: 'Zepto',
      location: 'Mumbai / Bengaluru, India',
      remote: false,
      workMode: 'ON_SITE',
      region: 'INDIA',
      experienceLevel: 'MID',
      sourcePlatform: 'LinkedIn',
      employmentType: 'Full-Time',
      salary: '₹32,00,000 - ₹50,00,000 / 32-50 LPA + ESOPs',
      skills: ['TypeScript', 'Next.js', 'React', 'Node.js', 'Redis'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 11).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-006',
    type: 'JOB',
    title: 'SDE-2 Distributed Storage & Catalog Engineer',
    description: 'Design and build petabyte-scale multi-tier catalog cache, real-time pricing pipelines, and high-concurrency Big Billion Days checkout services.',
    summary: 'Work on one of India largest e-commerce distributed backends processing millions of requests per second.',
    canonicalUrl: 'https://flipkartcareers.com/jobs/sde-2-storage',
    category: 'Distributed Systems',
    tags: ['java', 'cassandra', 'kafka', 'elasticsearch', 'distributed-systems', 'india'],
    score: {
      total: 94,
      freshness: 93,
      popularity: 95,
      developerValue: 95,
      technologyImpact: 94,
      reasons: ['Scale testing at hundreds of thousands TPS', 'Robust engineering mentorship'],
    },
    job: {
      company: 'Flipkart',
      location: 'Bengaluru, India',
      remote: false,
      workMode: 'HYBRID',
      region: 'INDIA',
      experienceLevel: 'MID',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '₹30,00,000 - ₹45,00,000 / 30-45 LPA + Stock Grants',
      skills: ['Java', 'Kafka', 'Cassandra', 'Elasticsearch', 'Microservices'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-007',
    type: 'JOB',
    title: 'Senior Software Engineer - Maps & Spatial Intelligence',
    description: 'Develop graph routing algorithms, ETAs prediction models, and spatial mapping tile services powering mobility for millions of riders across India and EMEA.',
    summary: 'Deep engineering in distributed graph computing, geospatial data structures, and real-time routing engines.',
    canonicalUrl: 'https://uber.com/careers/senior-software-engineer-maps',
    category: 'Geospatial & Distributed Systems',
    tags: ['golang', 'java', 'graph-algorithms', 'geospatial', 'kafka', 'india'],
    score: {
      total: 97,
      freshness: 96,
      popularity: 97,
      developerValue: 98,
      technologyImpact: 97,
      reasons: ['World-class engineering bar', 'Exceptional global tech compensation', 'Complex algorithmic challenges'],
    },
    job: {
      company: 'Uber India',
      location: 'Hyderabad / Bengaluru, India',
      remote: true,
      workMode: 'HYBRID',
      region: 'INDIA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'LinkedIn',
      employmentType: 'Full-Time',
      salary: '₹50,00,000 - ₹75,00,000 / 50-75 LPA + US RSUs',
      skills: ['Go', 'Java', 'Geospatial', 'Graph Algorithms', 'High-Scale Systems'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 16).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-008',
    type: 'JOB',
    title: 'Software Engineer II - Azure Edge & Cloud Networking',
    description: 'Build hyper-scale software-defined networking control planes, virtual network gateways, and edge compute services powering Azure worldwide.',
    summary: 'Core cloud networking engineering powering global internet backbone routes.',
    canonicalUrl: 'https://careers.microsoft.com/jobs/software-engineer-2-azure',
    category: 'Cloud Infrastructure',
    tags: ['c++', 'csharp', 'azure', 'sdn', 'networking', 'india'],
    score: {
      total: 95,
      freshness: 94,
      popularity: 96,
      developerValue: 96,
      technologyImpact: 95,
      reasons: ['Foundational cloud infrastructure', 'Stable high compensation and benefits'],
    },
    job: {
      company: 'Microsoft India',
      location: 'Hyderabad / Bengaluru, India',
      remote: true,
      workMode: 'HYBRID',
      region: 'INDIA',
      experienceLevel: 'MID',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '₹38,00,000 - ₹54,00,000 / 38-54 LPA + RSUs',
      skills: ['C++', 'C#', 'Cloud Networking', 'Distributed Systems', 'Azure'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-009',
    type: 'JOB',
    title: 'Senior Frontend Engineer - Developer Experience & API Tools',
    description: 'Build high-performance collaborative API testing client, Electron runtime optimizations, and web-worker driven request execution pipelines.',
    summary: 'Shape the daily API development workflow of over 35 million software engineers globally.',
    canonicalUrl: 'https://postman.com/company/careers/senior-frontend-engineer',
    category: 'Developer Tools & UI',
    tags: ['typescript', 'react', 'electron', 'web-workers', 'api', 'india'],
    score: {
      total: 96,
      freshness: 95,
      popularity: 96,
      developerValue: 97,
      technologyImpact: 96,
      reasons: ['Product used by every software developer', 'Deep frontend systems architecture'],
    },
    job: {
      company: 'Postman',
      location: 'Bengaluru, India / Remote',
      remote: true,
      workMode: 'REMOTE',
      region: 'INDIA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '₹36,00,000 - ₹52,00,000 / 36-52 LPA + Equity',
      skills: ['TypeScript', 'React', 'Electron', 'Performance', 'Web Workers'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-in-010',
    type: 'JOB',
    title: 'Compiler & Query Engine Systems Engineer',
    description: 'Design high-performance GraphQL and SQL execution planners, JIT compiler optimizations, and connector engines written in Rust and Haskell.',
    summary: 'Deep systems engineering at the boundary of programming language theory and database engines.',
    canonicalUrl: 'https://hasura.io/careers/compiler-engineer',
    category: 'Systems & Compilers',
    tags: ['rust', 'haskell', 'graphql', 'postgresql', 'compilers', 'india'],
    score: {
      total: 97,
      freshness: 96,
      popularity: 95,
      developerValue: 98,
      technologyImpact: 97,
      reasons: ['Rare systems & compilers engineering in India', '100% remote-first philosophy'],
    },
    job: {
      company: 'Hasura',
      location: 'Bengaluru, India / Remote Worldwide',
      remote: true,
      workMode: 'REMOTE',
      region: 'INDIA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '₹45,00,000 - ₹68,00,000 / 45-68 LPA + Equity',
      skills: ['Rust', 'Haskell', 'PostgreSQL', 'GraphQL', 'Compilers'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
    status: 'PROCESSED',
  },

  // ==========================================
  // GLOBAL REMOTE & WORLDWIDE TECH HUBS
  // ==========================================
  {
    _id: 'job-gl-001',
    type: 'JOB',
    title: 'Senior AI Systems Engineer (Inference Infrastructure)',
    description: 'Design and build high-throughput distributed inference pipelines, GPU cluster orchestration, and token streaming infra for Claude 3.7 reasoning models.',
    summary: 'Core engineering role focused on frontier model test-time compute scaling and sub-50ms inference.',
    canonicalUrl: 'https://careers.anthropic.com/jobs/ai-systems-engineer',
    category: 'AI Systems & GPU Compute',
    tags: ['rust', 'python', 'kubernetes', 'cuda', 'llm-infra', 'remote'],
    score: {
      total: 99,
      freshness: 99,
      popularity: 99,
      developerValue: 100,
      technologyImpact: 99,
      reasons: ['Frontier AI research and deployment', 'Top-of-market global compensation'],
    },
    job: {
      company: 'Anthropic',
      location: 'San Francisco, CA / Remote Global',
      remote: true,
      workMode: 'REMOTE',
      region: 'GLOBAL_REMOTE',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '$240,000 - $330,000 / Year + Equity',
      skills: ['Rust', 'Python', 'Kubernetes', 'CUDA', 'LLM Serving'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-gl-002',
    type: 'JOB',
    title: 'Distributed Training Platform Engineer',
    description: 'Build petabyte-scale GPU cluster schedulers, fault-tolerant checkpointing engines, and high-bandwidth interconnect fabric for next-gen frontier models.',
    summary: 'Accelerate training efficiency across massive clusters of tens of thousands of GPUs.',
    canonicalUrl: 'https://openai.com/careers/distributed-training-engineer',
    category: 'AI Infrastructure',
    tags: ['pytorch', 'cuda', 'hpc', 'python', 'distributed-systems'],
    score: {
      total: 98,
      freshness: 97,
      popularity: 99,
      developerValue: 99,
      technologyImpact: 98,
      reasons: ['Exascale compute systems', 'Direct frontier model training impact'],
    },
    job: {
      company: 'OpenAI',
      location: 'San Francisco, CA / Hybrid',
      remote: false,
      workMode: 'HYBRID',
      region: 'NORTH_AMERICA',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '$260,000 - $360,000 / Year + Equity',
      skills: ['PyTorch', 'Triton', 'GPU Clusters', 'InfiniBand', 'C++'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-gl-003',
    type: 'JOB',
    title: 'Staff Systems & Latency Engineer',
    description: 'Optimize globally distributed edge routing, zero-trust traffic meshes, and millisecond-level API payment gateways processing billions of daily transactions.',
    summary: 'Scale critical financial rail infrastructure processing billions of transactions per day.',
    canonicalUrl: 'https://stripe.com/jobs/staff-latency-engineer',
    category: 'Financial Infrastructure',
    tags: ['go', 'envoy', 'distributed-systems', 'networking', 'latency', 'remote'],
    score: {
      total: 97,
      freshness: 95,
      popularity: 96,
      developerValue: 98,
      technologyImpact: 97,
      reasons: ['Five-nines reliability engineering', 'Remote-first engineering culture'],
    },
    job: {
      company: 'Stripe',
      location: 'Remote (US, Canada, Europe, Worldwide)',
      remote: true,
      workMode: 'REMOTE',
      region: 'GLOBAL_REMOTE',
      experienceLevel: 'STAFF_PRINCIPAL',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '$220,000 - $295,000 / Year + Equity',
      skills: ['Go', 'Envoy', 'Distributed Tracing', 'Linux Internals', 'gRPC'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-gl-004',
    type: 'JOB',
    title: 'Senior Runtime Engineer (Workers & V8 Engine)',
    description: 'Advance the workerd open-source runtime powering Cloudflare Workers with next-generation WebAssembly, standard Web APIs, and isolated edge compute.',
    summary: 'Engineer the foundational execution layer running billions of requests per minute at 300+ PoPs worldwide.',
    canonicalUrl: 'https://cloudflare.com/careers/runtime-engineer',
    category: 'Edge Compute',
    tags: ['c++', 'rust', 'v8', 'webassembly', 'edge', 'remote'],
    score: {
      total: 96,
      freshness: 94,
      popularity: 95,
      developerValue: 97,
      technologyImpact: 96,
      reasons: ['Pioneering serverless edge runtime', 'Open-source workerd codebase'],
    },
    job: {
      company: 'Cloudflare',
      location: 'Remote Worldwide (Americas, EMEA, APAC)',
      remote: true,
      workMode: 'REMOTE',
      region: 'GLOBAL_REMOTE',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'LinkedIn',
      employmentType: 'Full-Time',
      salary: '$190,000 - $260,000 / Year + Equity',
      skills: ['C++', 'Rust', 'V8 Internals', 'POSIX', 'WebAssembly'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-gl-005',
    type: 'JOB',
    title: 'Staff Edge Framework Engineer (Next.js & Turbopack)',
    description: 'Architect Next.js compilation pipelines, partial prerendering, and Turbopack incremental build graph optimization for enterprise React applications.',
    summary: 'Shape the future of modern web development across millions of production applications worldwide.',
    canonicalUrl: 'https://vercel.com/careers/framework-engineer',
    category: 'Developer Experience',
    tags: ['nextjs', 'react', 'rust', 'typescript', 'turbopack', 'remote'],
    score: {
      total: 95,
      freshness: 93,
      popularity: 96,
      developerValue: 96,
      technologyImpact: 95,
      reasons: ['Industry standard framework', 'Rust compiler architecture', '100% remote'],
    },
    job: {
      company: 'Vercel',
      location: 'Remote Worldwide',
      remote: true,
      workMode: 'REMOTE',
      region: 'GLOBAL_REMOTE',
      experienceLevel: 'STAFF_PRINCIPAL',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '$200,000 - $275,000 / Year + Equity',
      skills: ['TypeScript', 'Rust', 'React 19', 'Next.js App Router', 'Turbopack'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 15).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-gl-006',
    type: 'JOB',
    title: 'Database Systems & Raft Consensus Engineer',
    description: 'Work on distributed PostgreSQL replication, Realtime Elixir broadcast nodes, and Raft consensus storage engines powering thousands of backend projects.',
    summary: 'Build open-source Firebase alternative powering hundreds of thousands of developers.',
    canonicalUrl: 'https://supabase.com/careers/database-systems-engineer',
    category: 'Database Systems',
    tags: ['postgresql', 'elixir', 'rust', 'raft', 'distributed-systems', 'remote'],
    score: {
      total: 96,
      freshness: 94,
      popularity: 95,
      developerValue: 97,
      technologyImpact: 96,
      reasons: ['Open source first culture', '100% remote global hiring', 'Deep database internals'],
    },
    job: {
      company: 'Supabase',
      location: 'Remote Worldwide',
      remote: true,
      workMode: 'REMOTE',
      region: 'GLOBAL_REMOTE',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'Company Careers',
      employmentType: 'Full-Time',
      salary: '$165,000 - $230,000 / Year + Token/Equity',
      skills: ['PostgreSQL', 'Elixir', 'Rust', 'Raft Consensus', 'WAL'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 19).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-gl-007',
    type: 'JOB',
    title: 'Senior High-Throughput Ingestion Engineer',
    description: 'Scale streaming telemetry intake engines handling over 50 trillion metrics, traces, and logs every single day with sub-second querying.',
    summary: 'Extreme data volume distributed systems engineering in Go and Kafka.',
    canonicalUrl: 'https://datadoghq.com/careers/senior-ingestion-engineer',
    category: 'Observability & Streaming',
    tags: ['golang', 'kafka', 'cassandra', 'grpc', 'streaming', 'remote'],
    score: {
      total: 94,
      freshness: 92,
      popularity: 94,
      developerValue: 95,
      technologyImpact: 94,
      reasons: ['Fifty trillion events daily scale', 'European or US remote flexibility'],
    },
    job: {
      company: 'Datadog',
      location: 'Paris, France / Amsterdam / Remote EU',
      remote: true,
      workMode: 'REMOTE',
      region: 'EUROPE',
      experienceLevel: 'SENIOR',
      sourcePlatform: 'LinkedIn',
      employmentType: 'Full-Time',
      salary: '€110,000 - €155,000 / Year + Stock Options',
      skills: ['Go', 'Kafka', 'Cassandra', 'Distributed Tracing', 'gRPC'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 23).toISOString(),
    status: 'PROCESSED',
  },

  // ==========================================
  // FRONTIER AI TOOLS & MODELS
  // ==========================================
  {
    _id: 'tool-001',
    type: 'AI_TOOL',
    title: 'Claude 3.7 Sonnet Hybrid Reasoning Engine',
    description: 'Anthropic introduces the first frontier hybrid reasoning model combining instant streaming responses with user-directed extended thinking budgets.',
    summary: 'Next-generation frontier AI model with dynamic test-time compute scaling.',
    canonicalUrl: 'https://anthropic.com/news/claude-3-7-sonnet',
    category: 'AI & Machine Learning',
    tags: ['ai', 'llm', 'reasoning', 'anthropic', 'frontier-model'],
    score: {
      total: 99,
      freshness: 100,
      popularity: 99,
      developerValue: 99,
      technologyImpact: 100,
      reasons: ['Breakthrough hybrid reasoning capability', 'Highest coding benchmark performance'],
    },
    tool: {
      pricingModel: 'PAID',
      isOpenSource: false,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-002',
    type: 'AI_TOOL',
    title: 'DeepSeek-R1 Open-Weights Reasoning Architecture',
    description: 'Open-weights frontier reasoning model trained via large-scale reinforcement learning without supervised fine-tuning cold start.',
    summary: 'Open-weights architecture demonstrating math, logic, and code generation competitive with closed frontier models.',
    canonicalUrl: 'https://github.com/deepseek-ai/DeepSeek-R1',
    category: 'Open Source AI',
    tags: ['deepseek', 'reasoning', 'open-weights', 'rl', 'llm'],
    score: {
      total: 98,
      freshness: 98,
      popularity: 100,
      developerValue: 99,
      technologyImpact: 99,
      reasons: ['Open weights release', 'Paradigm shift in RL training recipes'],
    },
    tool: {
      pricingModel: 'OPEN_SOURCE',
      isOpenSource: true,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-003',
    type: 'AI_TOOL',
    title: 'vLLM High-Throughput Inference Engine',
    description: 'High-throughput and memory-efficient LLM serving engine powered by PagedAttention and continuous batching.',
    summary: 'Industry standard distributed serving infrastructure offering 2x-4x throughput over vanilla transformers.',
    canonicalUrl: 'https://github.com/vllm-project/vllm',
    category: 'Inference Infrastructure',
    tags: ['inference', 'paged-attention', 'python', 'cuda', 'serving'],
    score: {
      total: 96,
      freshness: 95,
      popularity: 97,
      developerValue: 98,
      technologyImpact: 96,
      reasons: ['PagedAttention algorithm standard', 'Universal production adoption'],
    },
    tool: {
      pricingModel: 'OPEN_SOURCE',
      isOpenSource: true,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-004',
    type: 'AI_TOOL',
    title: 'Cursor Composer Agentic IDE',
    description: 'AI-first code editor featuring terminal execution, background indexing, and multi-file semantic code refactoring.',
    summary: 'Next-generation development environment accelerating software engineering velocity.',
    canonicalUrl: 'https://cursor.com',
    category: 'Developer Experience',
    tags: ['ide', 'agent', 'editor', 'coding-assistant', 'developer-tools'],
    score: {
      total: 95,
      freshness: 94,
      popularity: 98,
      developerValue: 97,
      technologyImpact: 95,
      reasons: ['Fastest growing AI editor', 'Exceptional DX feedback loop'],
    },
    tool: {
      pricingModel: 'FREEMIUM',
      isOpenSource: false,
      hasApi: false,
    },
    publishedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-005',
    type: 'AI_TOOL',
    title: 'Biome 1.9 Rust Web Toolchain',
    description: 'Sub-millisecond formatter, linter, and type checker for JavaScript and TypeScript written entirely in Rust.',
    summary: 'Ultra-fast drop-in replacement for ESLint and Prettier for large monorepos.',
    canonicalUrl: 'https://biomejs.dev',
    category: 'Developer Tools',
    tags: ['rust', 'linter', 'formatter', 'typescript', 'toolchain'],
    score: {
      total: 93,
      freshness: 90,
      popularity: 92,
      developerValue: 95,
      technologyImpact: 92,
      reasons: ['10x-30x faster than traditional JS linters', 'Zero config unified architecture'],
    },
    tool: {
      pricingModel: 'OPEN_SOURCE',
      isOpenSource: true,
      hasApi: false,
    },
    publishedAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-006',
    type: 'AI_TOOL',
    title: 'Langfuse Open Source LLM Observability',
    description: 'Open-source tracing, prompt management, and automated evaluation platform for LLM applications in production.',
    summary: 'Deep tracing and latency telemetry for complex multi-step agentic workflows.',
    canonicalUrl: 'https://langfuse.com',
    category: 'AI Observability',
    tags: ['observability', 'tracing', 'llmops', 'evals', 'open-source'],
    score: {
      total: 92,
      freshness: 91,
      popularity: 90,
      developerValue: 94,
      technologyImpact: 91,
      reasons: ['Comprehensive OpenTelemetry traces', 'Self-hostable MIT license'],
    },
    tool: {
      pricingModel: 'FREEMIUM',
      isOpenSource: true,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    status: 'PROCESSED',
  },

  // ==========================================
  // FAST-GROWING OPEN SOURCE REPOSITORIES
  // ==========================================
  {
    _id: 'repo-001',
    type: 'REPOSITORY',
    title: 'anthropics/anthropic-sdk-typescript',
    description: 'Official TypeScript library for the Anthropic Claude API with streaming, tool calling, and full type safety.',
    summary: 'Essential SDK for integrating Claude 3.7 into Node.js, Deno, Bun, and Edge runtime applications.',
    canonicalUrl: 'https://github.com/anthropics/anthropic-sdk-typescript',
    category: 'Developer Tools',
    tags: ['typescript', 'sdk', 'anthropic', 'api', 'ai'],
    score: {
      total: 95,
      freshness: 94,
      popularity: 96,
      developerValue: 97,
      technologyImpact: 94,
      reasons: ['Critical developer infrastructure', 'Active weekly releases'],
    },
    repository: {
      ownerRepo: 'anthropics/anthropic-sdk-typescript',
      stars: 5240,
      forks: 412,
      language: 'TypeScript',
      starsGrowth24h: 320,
    },
    publishedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'repo-002',
    type: 'REPOSITORY',
    title: 'astral-sh/uv',
    description: 'An extremely fast Python package and project manager, written in Rust, replacing pip, pip-tools, and virtualenv.',
    summary: 'Sub-100ms Python dependency resolution and virtualenv creation transforming Python developer workflows.',
    canonicalUrl: 'https://github.com/astral-sh/uv',
    category: 'Package Managers',
    tags: ['rust', 'python', 'package-manager', 'developer-tools'],
    score: {
      total: 97,
      freshness: 96,
      popularity: 99,
      developerValue: 99,
      technologyImpact: 97,
      reasons: ['10x-100x performance leap over pip', 'Unified Python workspace manager'],
    },
    repository: {
      ownerRepo: 'astral-sh/uv',
      stars: 42100,
      forks: 1450,
      language: 'Rust',
      starsGrowth24h: 680,
    },
    publishedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'repo-003',
    type: 'REPOSITORY',
    title: 'shadcn/ui',
    description: 'Beautifully designed components that you can copy and paste into your apps. Accessible, customizable, and open source.',
    summary: 'De-facto standard design component architecture for React, Next.js, and Tailwind CSS.',
    canonicalUrl: 'https://github.com/shadcn/ui',
    category: 'Frontend & UI',
    tags: ['react', 'tailwind', 'components', 'design-system', 'typescript'],
    score: {
      total: 96,
      freshness: 91,
      popularity: 100,
      developerValue: 98,
      technologyImpact: 95,
      reasons: ['Revolutionary component distribution model', 'Pervasive ecosystem adoption'],
    },
    repository: {
      ownerRepo: 'shadcn/ui',
      stars: 79200,
      forks: 7100,
      language: 'TypeScript',
      starsGrowth24h: 410,
    },
    publishedAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    status: 'PROCESSED',
  },

  // ==========================================
  // TECH NEWS & CRITICAL SECURITY ADVISORIES
  // ==========================================
  {
    _id: 'sec-001',
    type: 'SECURITY',
    title: 'CVE-2025-24970: Critical HTTP/2 Multiplexing Desync Advisory',
    description: 'High-severity vulnerability discovered in reverse proxy multiplexing engines allowing unauthorized cache poisoning and request desynchronization.',
    summary: 'Security engineers advise immediate upgrade of edge load balancers and ingress controllers.',
    canonicalUrl: 'https://nvd.nist.gov/vuln/detail/CVE-2025-24970',
    category: 'Security & CVE',
    tags: ['cve', 'security', 'http2', 'reverse-proxy', 'advisory'],
    score: {
      total: 99,
      freshness: 100,
      popularity: 96,
      developerValue: 99,
      technologyImpact: 100,
      reasons: ['Critical CVSS 9.8 advisory', 'Affects widespread edge infrastructure'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'news-001',
    type: 'NEWS',
    title: 'Next.js 15.2 Released with Partial Prerendering GA',
    description: 'Vercel ships Next.js 15.2 stabilizing PPR, reducing initial TTFB by up to 70% while maintaining dynamic personalization streaming.',
    summary: 'Major milestone combining the speed of static delivery with the flexibility of server streaming.',
    canonicalUrl: 'https://nextjs.org/blog/next-15-2',
    category: 'Framework Releases',
    tags: ['nextjs', 'react', 'performance', 'web-development'],
    score: {
      total: 93,
      freshness: 94,
      popularity: 95,
      developerValue: 94,
      technologyImpact: 92,
      reasons: ['Major architectural framework upgrade', 'Broad developer reach'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 11).toISOString(),
    status: 'PROCESSED',
  },
];
