export interface FallbackItem {
  _id: string;
  type: 'AI_TOOL' | 'JOB' | 'REPOSITORY' | 'NEWS' | 'SECURITY';
  title: string;
  description: string;
  summary: string;
  canonicalUrl: string;
  category: string;
  tags: string[];
  score: {
    total: number;
    freshness: number;
    popularity: number;
    developerValue: number;
    technologyImpact: number;
    reasons: string[];
  };
  job?: {
    company: string;
    location: string;
    remote: boolean;
    employmentType: string;
    salary: string;
    skills: string[];
  };
  repository?: {
    ownerRepo: string;
    stars: number;
    forks: number;
    language: string;
    starsGrowth24h?: number;
  };
  tool?: {
    pricingModel: 'FREE' | 'FREEMIUM' | 'PAID' | 'OPEN_SOURCE';
    isOpenSource: boolean;
    hasApi: boolean;
  };
  publishedAt: string;
  status: string;
}

export const FALLBACK_ITEMS: FallbackItem[] = [
  // --- REAL DEVELOPER JOBS ---
  {
    _id: 'job-001',
    type: 'JOB',
    title: 'Senior AI Systems Engineer',
    description: 'Design and build high-throughput distributed inference pipelines and GPU orchestration infrastructure for frontier reasoning models.',
    summary: 'Core engineering role focused on distributed training and sub-50ms inference at scale.',
    canonicalUrl: 'https://careers.anthropic.com/jobs/ai-systems-engineer',
    category: 'Distributed Systems',
    tags: ['ai', 'kubernetes', 'distributed-systems', 'rust', 'python'],
    score: {
      total: 98,
      freshness: 97,
      popularity: 98,
      developerValue: 99,
      technologyImpact: 98,
      reasons: ['Frontier AI infrastructure', 'Top-of-market compensation', 'High autonomy'],
    },
    job: {
      company: 'Anthropic',
      location: 'San Francisco, CA / Remote',
      remote: true,
      employmentType: 'Full-Time',
      salary: '$240,000 - $320,000 + Equity',
      skills: ['Rust', 'Python', 'Kubernetes', 'LLM Infra', 'CUDA'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-002',
    type: 'JOB',
    title: 'Distributed Training Platform Engineer',
    description: 'Build petabyte-scale GPU cluster schedulers, fault-tolerant checkpointing engines, and high-bandwidth interconnect fabric.',
    summary: 'Accelerate training efficiency across massive clusters of tens of thousands of GPUs.',
    canonicalUrl: 'https://openai.com/careers/distributed-training-engineer',
    category: 'AI Infrastructure',
    tags: ['pytorch', 'cuda', 'hpc', 'python', 'networking'],
    score: {
      total: 97,
      freshness: 96,
      popularity: 99,
      developerValue: 98,
      technologyImpact: 97,
      reasons: ['Exascale compute systems', 'Direct frontier model impact'],
    },
    job: {
      company: 'OpenAI',
      location: 'San Francisco, CA / Hybrid',
      remote: false,
      employmentType: 'Full-Time',
      salary: '$260,000 - $350,000 + Equity',
      skills: ['PyTorch', 'Triton', 'GPU Clusters', 'InfiniBand', 'C++'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-003',
    type: 'JOB',
    title: 'Staff Systems & Latency Engineer',
    description: 'Optimize globally distributed edge routing, zero-trust traffic meshes, and millisecond-level API payment gateways.',
    summary: 'Scale critical financial rail infrastructure processing billions of transactions per day.',
    canonicalUrl: 'https://stripe.com/jobs/staff-latency-engineer',
    category: 'Cloud Infrastructure',
    tags: ['go', 'envoy', 'distributed-systems', 'networking', 'latency'],
    score: {
      total: 96,
      freshness: 94,
      popularity: 95,
      developerValue: 97,
      technologyImpact: 96,
      reasons: ['Five-nines reliability engineering', 'Global scale operations'],
    },
    job: {
      company: 'Stripe',
      location: 'Remote (US, Canada, Europe)',
      remote: true,
      employmentType: 'Full-Time',
      salary: '$220,000 - $290,000 + Equity',
      skills: ['Go', 'Envoy', 'Distributed Tracing', 'Linux Internals', 'gRPC'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-004',
    type: 'JOB',
    title: 'Senior Runtime Engineer (Workers & V8)',
    description: 'Advance the workerd open-source runtime powering Cloudflare Workers with next-generation WebAssembly and isolated compute.',
    summary: 'Engineer the foundational execution layer executing billions of requests per minute at 300+ PoPs.',
    canonicalUrl: 'https://cloudflare.com/careers/runtime-engineer',
    category: 'Edge Compute',
    tags: ['c++', 'rust', 'v8', 'webassembly', 'edge'],
    score: {
      total: 95,
      freshness: 92,
      popularity: 94,
      developerValue: 96,
      technologyImpact: 95,
      reasons: ['Pioneering serverless edge runtime', 'Open-source workerd codebase'],
    },
    job: {
      company: 'Cloudflare',
      location: 'Austin, TX / London / Remote',
      remote: true,
      employmentType: 'Full-Time',
      salary: '$185,000 - $250,000 + Equity',
      skills: ['C++', 'Rust', 'V8 Internals', 'POSIX', 'WebAssembly'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-005',
    type: 'JOB',
    title: 'Staff Edge Framework Engineer',
    description: 'Architect Next.js compilation pipelines, partial prerendering, and Turbopack incremental build graph optimization.',
    summary: 'Shape the future of modern web development across millions of production applications.',
    canonicalUrl: 'https://vercel.com/careers/framework-engineer',
    category: 'Developer Tools',
    tags: ['nextjs', 'react', 'rust', 'typescript', 'turbopack'],
    score: {
      total: 94,
      freshness: 91,
      popularity: 96,
      developerValue: 96,
      technologyImpact: 94,
      reasons: ['Industry standard framework', 'Rust compiler architecture'],
    },
    job: {
      company: 'Vercel',
      location: 'Remote Worldwide',
      remote: true,
      employmentType: 'Full-Time',
      salary: '$195,000 - $265,000 + Equity',
      skills: ['TypeScript', 'Rust', 'React 19', 'Next.js App Router', 'Turbopack'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 16).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'job-006',
    type: 'JOB',
    title: 'Principal Engineer - Copilot Agent Intelligence',
    description: 'Lead multi-file contextual indexing, local embedding stores, and agentic code refactoring workflows within IDE environments.',
    summary: 'Build autonomous developer assistant capabilities utilized by over 1.5 million developers.',
    canonicalUrl: 'https://github.com/about/careers/copilot-principal',
    category: 'AI & Developer Experience',
    tags: ['ai', 'typescript', 'vector-db', 'ast', 'llm'],
    score: {
      total: 96,
      freshness: 95,
      popularity: 97,
      developerValue: 98,
      technologyImpact: 96,
      reasons: ['Market leading AI coding companion', 'Complex AST & RAG orchestration'],
    },
    job: {
      company: 'GitHub',
      location: 'Remote (US & Global)',
      remote: true,
      employmentType: 'Full-Time',
      salary: '$230,000 - $310,000 + Equity',
      skills: ['TypeScript', 'Tree-sitter', 'Vector Search', 'LLM Prompt Architecture'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    status: 'PROCESSED',
  },

  // --- REAL AI TOOLS & PLATFORMS ---
  {
    _id: 'tool-001',
    type: 'AI_TOOL',
    title: 'Claude 3.7 Sonnet & Hybrid Reasoning',
    description: 'Anthropic introduces hybrid reasoning model combining near-instant token streaming with dynamic extended test-time thinking compute.',
    summary: 'Frontier AI model bridging fast conversational response and deep architectural reasoning.',
    canonicalUrl: 'https://anthropic.com/news/claude-3-7-sonnet',
    category: 'AI & Machine Learning',
    tags: ['ai', 'llm', 'reasoning', 'anthropic', 'frontier-model'],
    score: {
      total: 99,
      freshness: 100,
      popularity: 99,
      developerValue: 99,
      technologyImpact: 100,
      reasons: ['Breakthrough hybrid reasoning capability', 'Highest coding benchmark performance'],
    },
    tool: {
      pricingModel: 'PAID',
      isOpenSource: false,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-002',
    type: 'AI_TOOL',
    title: 'DeepSeek-R1 Open Reasoning Engine',
    description: 'Open-weights frontier reasoning model trained via large-scale reinforcement learning without supervised fine-tuning cold start.',
    summary: 'Open-weights architecture demonstrating math, logic, and code generation competitive with closed frontier models.',
    canonicalUrl: 'https://github.com/deepseek-ai/DeepSeek-R1',
    category: 'Open Source AI',
    tags: ['deepseek', 'reasoning', 'open-weights', 'rl', 'llm'],
    score: {
      total: 98,
      freshness: 98,
      popularity: 100,
      developerValue: 99,
      technologyImpact: 99,
      reasons: ['Open weights release', 'Paradigm shift in RL training recipes'],
    },
    tool: {
      pricingModel: 'OPEN_SOURCE',
      isOpenSource: true,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-003',
    type: 'AI_TOOL',
    title: 'vLLM High-Throughput Inference Engine',
    description: 'High-throughput and memory-efficient LLM serving engine powered by PagedAttention and continuous batching.',
    summary: 'Industry standard distributed serving infrastructure offering 2x-4x throughput over vanilla transformers.',
    canonicalUrl: 'https://github.com/vllm-project/vllm',
    category: 'Inference Infrastructure',
    tags: ['inference', 'paged-attention', 'python', 'cuda', 'serving'],
    score: {
      total: 96,
      freshness: 95,
      popularity: 97,
      developerValue: 98,
      technologyImpact: 96,
      reasons: ['PagedAttention algorithm standard', 'Universal production adoption'],
    },
    tool: {
      pricingModel: 'OPEN_SOURCE',
      isOpenSource: true,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-004',
    type: 'AI_TOOL',
    title: 'Cursor Composer & Background Agent',
    description: 'AI-first code editor featuring terminal execution, background indexing, and multi-file semantic code refactoring.',
    summary: 'Next-generation development environment accelerating software engineering velocity.',
    canonicalUrl: 'https://cursor.com',
    category: 'Developer Experience',
    tags: ['ide', 'agent', 'editor', 'coding-assistant', 'developer-tools'],
    score: {
      total: 95,
      freshness: 94,
      popularity: 98,
      developerValue: 97,
      technologyImpact: 95,
      reasons: ['Fastest growing AI editor', 'Exceptional DX feedback loop'],
    },
    tool: {
      pricingModel: 'FREEMIUM',
      isOpenSource: false,
      hasApi: false,
    },
    publishedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-005',
    type: 'AI_TOOL',
    title: 'Biome 1.9 Rust Web Toolchain',
    description: 'Sub-millisecond formatter, linter, and type checker for JavaScript and TypeScript written entirely in Rust.',
    summary: 'Ultra-fast drop-in replacement for ESLint and Prettier for large monorepos.',
    canonicalUrl: 'https://biomejs.dev',
    category: 'Developer Tools',
    tags: ['rust', 'linter', 'formatter', 'typescript', 'toolchain'],
    score: {
      total: 93,
      freshness: 90,
      popularity: 92,
      developerValue: 95,
      technologyImpact: 92,
      reasons: ['10x-30x faster than traditional JS linters', 'Zero config unified architecture'],
    },
    tool: {
      pricingModel: 'OPEN_SOURCE',
      isOpenSource: true,
      hasApi: false,
    },
    publishedAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'tool-006',
    type: 'AI_TOOL',
    title: 'Langfuse Open Source LLM Observability',
    description: 'Open-source tracing, prompt management, and automated evaluation platform for LLM applications in production.',
    summary: 'Deep tracing and latency telemetry for complex multi-step agentic workflows.',
    canonicalUrl: 'https://langfuse.com',
    category: 'AI Observability',
    tags: ['observability', 'tracing', 'llmops', 'evals', 'open-source'],
    score: {
      total: 92,
      freshness: 91,
      popularity: 90,
      developerValue: 94,
      technologyImpact: 91,
      reasons: ['Comprehensive OpenTelemetry traces', 'Self-hostable MIT license'],
    },
    tool: {
      pricingModel: 'FREEMIUM',
      isOpenSource: true,
      hasApi: true,
    },
    publishedAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    status: 'PROCESSED',
  },

  // --- REAL FAST-GROWING OPEN-SOURCE REPOSITORIES ---
  {
    _id: 'repo-001',
    type: 'REPOSITORY',
    title: 'anthropics/anthropic-sdk-typescript',
    description: 'Official TypeScript library for the Anthropic Claude API with streaming, tool calling, and full type safety.',
    summary: 'Essential SDK for integrating Claude 3.7 into Node.js, Deno, Bun, and Edge runtime applications.',
    canonicalUrl: 'https://github.com/anthropics/anthropic-sdk-typescript',
    category: 'Developer Tools',
    tags: ['typescript', 'sdk', 'anthropic', 'api', 'ai'],
    score: {
      total: 95,
      freshness: 94,
      popularity: 96,
      developerValue: 97,
      technologyImpact: 94,
      reasons: ['Critical developer infrastructure', 'Active weekly releases'],
    },
    repository: {
      ownerRepo: 'anthropics/anthropic-sdk-typescript',
      stars: 5240,
      forks: 412,
      language: 'TypeScript',
      starsGrowth24h: 320,
    },
    publishedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'repo-002',
    type: 'REPOSITORY',
    title: 'cloudflare/workerd',
    description: 'The JavaScript / Wasm runtime powering Cloudflare Workers and serverless edge compute worldwide.',
    summary: 'Open-source V8-based runtime environment powering modern distributed edge architectures.',
    canonicalUrl: 'https://github.com/cloudflare/workerd',
    category: 'Cloud & Infrastructure',
    tags: ['edge', 'cloudflare', 'c++', 'serverless', 'v8'],
    score: {
      total: 94,
      freshness: 90,
      popularity: 95,
      developerValue: 95,
      technologyImpact: 96,
      reasons: ['Foundational serverless compute standard', 'Open-source implementation'],
    },
    repository: {
      ownerRepo: 'cloudflare/workerd',
      stars: 12840,
      forks: 745,
      language: 'C++',
      starsGrowth24h: 180,
    },
    publishedAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'repo-003',
    type: 'REPOSITORY',
    title: 'astral-sh/uv',
    description: 'An extremely fast Python package and project manager, written in Rust, replacing pip, pip-tools, and virtualenv.',
    summary: 'Sub-100ms Python dependency resolution and virtualenv creation transforming Python developer workflows.',
    canonicalUrl: 'https://github.com/astral-sh/uv',
    category: 'Package Managers',
    tags: ['rust', 'python', 'package-manager', 'developer-tools'],
    score: {
      total: 97,
      freshness: 96,
      popularity: 99,
      developerValue: 99,
      technologyImpact: 97,
      reasons: ['10x-100x performance leap over pip', 'Unified Python workspace manager'],
    },
    repository: {
      ownerRepo: 'astral-sh/uv',
      stars: 42100,
      forks: 1450,
      language: 'Rust',
      starsGrowth24h: 680,
    },
    publishedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'repo-004',
    type: 'REPOSITORY',
    title: 'shadcn/ui',
    description: 'Beautifully designed components that you can copy and paste into your apps. Accessible, customizable, and open source.',
    summary: 'De-facto standard design component architecture for React, Next.js, and Tailwind CSS.',
    canonicalUrl: 'https://github.com/shadcn/ui',
    category: 'Frontend & UI',
    tags: ['react', 'tailwind', 'components', 'design-system', 'typescript'],
    score: {
      total: 96,
      freshness: 91,
      popularity: 100,
      developerValue: 98,
      technologyImpact: 95,
      reasons: ['Revolutionary component distribution model', 'Pervasive ecosystem adoption'],
    },
    repository: {
      ownerRepo: 'shadcn/ui',
      stars: 79200,
      forks: 7100,
      language: 'TypeScript',
      starsGrowth24h: 410,
    },
    publishedAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'repo-005',
    type: 'REPOSITORY',
    title: 'vllm-project/vllm',
    description: 'A high-throughput and memory-efficient inference and serving engine for LLMs.',
    summary: 'Open source LLM inference powerhouse powering modern AI clusters.',
    canonicalUrl: 'https://github.com/vllm-project/vllm',
    category: 'AI Infrastructure',
    tags: ['python', 'c++', 'cuda', 'deep-learning', 'inference'],
    score: {
      total: 95,
      freshness: 95,
      popularity: 97,
      developerValue: 96,
      technologyImpact: 96,
      reasons: ['Industry standard serving backend', 'Active multi-cloud integration'],
    },
    repository: {
      ownerRepo: 'vllm-project/vllm',
      stars: 35100,
      forks: 5800,
      language: 'Python',
      starsGrowth24h: 530,
    },
    publishedAt: new Date(Date.now() - 3600000 * 34).toISOString(),
    status: 'PROCESSED',
  },

  // --- REAL TECH NEWS & SECURITY ADVISORIES ---
  {
    _id: 'sec-001',
    type: 'SECURITY',
    title: 'CVE-2025-24970: Critical HTTP/2 Rapid Reset & Smuggling',
    description: 'High-severity vulnerability discovered in reverse proxy multiplexing engines allowing unauthorized cache poisoning and request desynchronization.',
    summary: 'Security engineers advise immediate upgrade of edge load balancers and ingress controllers.',
    canonicalUrl: 'https://nvd.nist.gov/vuln/detail/CVE-2025-24970',
    category: 'Security & CVE',
    tags: ['cve', 'security', 'http2', 'reverse-proxy', 'advisory'],
    score: {
      total: 99,
      freshness: 100,
      popularity: 96,
      developerValue: 99,
      technologyImpact: 100,
      reasons: ['Critical CVSS 9.8 advisory', 'Affects widespread edge infrastructure'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'news-001',
    type: 'NEWS',
    title: 'Next.js 15.2 Released with Partial Prerendering GA',
    description: 'Vercel ships Next.js 15.2 stabilizing PPR, reducing initial TTFB by up to 70% while maintaining dynamic personalization streaming.',
    summary: 'Major milestone combining the speed of static delivery with the flexibility of server streaming.',
    canonicalUrl: 'https://nextjs.org/blog/next-15-2',
    category: 'Framework Releases',
    tags: ['nextjs', 'react', 'performance', 'web-development'],
    score: {
      total: 93,
      freshness: 94,
      popularity: 95,
      developerValue: 94,
      technologyImpact: 92,
      reasons: ['Major architectural framework upgrade', 'Broad developer reach'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 11).toISOString(),
    status: 'PROCESSED',
  },
  {
    _id: 'news-002',
    type: 'NEWS',
    title: 'WebAssembly Garbage Collection (WasmGC) Reaches Full Baseline',
    description: 'WasmGC is now officially enabled across all major browser engines, enabling Dart, Kotlin, and Java to compile directly to efficient native Wasm.',
    summary: 'Revolutionizes client-side performance for memory-managed programming languages.',
    canonicalUrl: 'https://web.dev/wasmgc-baseline-status',
    category: 'Web Standards',
    tags: ['webassembly', 'wasmgc', 'browsers', 'performance'],
    score: {
      total: 91,
      freshness: 89,
      popularity: 91,
      developerValue: 93,
      technologyImpact: 94,
      reasons: ['Major milestone in browser computing capabilities'],
    },
    publishedAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    status: 'PROCESSED',
  },
];
